# Generated by Django 5.2.7 on 2025-11-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_materia_user_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_estudiantes', models.BooleanField(default=False)),
                ('publico_profesores', models.BooleanField(default=False)),
                ('publico_general', models.BooleanField(default=False)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('cupo', models.PositiveIntegerField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
